#
# This script is generated by sshy cli
#
# when called it needs PUBKEY to be registered

BLUE="\e[34m";
RESET="\e[0m";

SSH_DIR="${HOME}/.ssh"
AUTHORIZED_FILE_PATH="${SSH_DIR}/authorized_keys";

echo -e "${BLUE}##########${RESET}";

if [ ! -f "${AUTHORIZED_FILE_PATH}" ]; then
  touch "${AUTHORIZED_FILE_PATH}";
  echo "[created] ${AUTHORIZED_FILE_PATH}";
else
  echo "[exists] ${AUTHORIZED_FILE_PATH}";
fi

echo "${PUBKEY}" >> "${AUTHORIZED_FILE_PATH}";

echo -e "${BLUE}##########${RESET}";